#
# - Create droplets
# - Configure a non root user with password connection enable
#
---
- hosts: localhost
  gather_facts: false
  vars:
    ## Specify your personnal token access
    do_token: ''

    ## First Way to create droplet : using a single admin ssh key
    do_authentication: 'admin_key'
    do_admin_pub_key_name: ''
    do_admin_pub_key: ''
    droplets:
      - for: "The user"
        name: "thuser"
  roles:
    - create-droplets
- hosts: droplets
  vars:
    droplets_username: user
    droplets_password: user
  roles:
    - password-user